name: Test frontend
on:
  push:
    branches:
      - master
#     paths:
#       - 'frontend/**'
jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install, Lint and Run Tests
        working-directory: frontend
        run: |
          npm ci
          npm run lint
          npm run test
  build-frontend:
    needs: test-frontend
    runs-on: ubuntu-latest
    outputs:
      size: ${{ steps.build.outputs.SIZE }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install an Build
        id: build
        working-directory: frontend
        run: |
          npm ci
          npm run build
          cp -rf ../.git/ out/
          touch out/.nojekyll
          echo "SIZE=$(du -sh out | awk '{print $1}')" >> $GITHUB_OUTPUT
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend
          path: frontend/out
  deploy-frontend:
    needs: build-frontend
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: frontend
      - name: Output from build
        run: |
          printf 'Out Size in Build Step:\n%s\n' "${{ needs.build-frontend.outputs.size }}"
          printf 'Out Size in Download Artifact Files:\n%s\n' "$(du -sh .)"
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          BRANCH: gh-pages
          FOLDER: .
          CLEAN: true
