name: Test frontend
on: [ push ]
jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - run: npm ci
        working-directory: frontend
      - run: npm run test
        working-directory: frontend
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install an Build
        working-directory: frontend
        run: |
          npm ci
          npm run build
          touch out/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: frontend/out
          CLEAN: true
