name: Test frontend
on:
  push:
    branches:
      - master
#     paths:
#       - 'frontend/**'
jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install, Lint and Run Tests
        working-directory: frontend
        run: |
          npm ci
          npm run lint
          npm run test
  build-frontend:
    needs: test-frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install an Build
        working-directory: frontend
        run: |
          npm ci
          npm run build
          touch out/.nojekyll
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend
          path: |
            frontend/out
            .git/
  deploy-frontend:
    needs: build-frontend
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: frontend
      - name: Output Content
        run: ls -la
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          BRANCH: gh-pages
          FOLDER: .
          CLEAN: true
