name: A new issue has been opened
on:
  issues:
    types: [ opened ]
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          run: echo "$GITHUB_CONTEXT"
      - name: Output issue context
        env:
          ISSUE_CONTEXT: ${{ toJson(github.event.issue) }}
          run: echo "$ISSUE_CONTEXT"
      - name: Output issue body
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
          run: echo "$ISSUE_BODY"
      - name: Output issue title
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
          run: echo "$ISSUE_TITLE"
      - name: Output issue number
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          run: echo "$ISSUE_NUMBER"
      - name: Output issue labels
        env:
          ISSUE_LABELS: ${{ toJson(github.event.issue.labels) }}
          run: echo "$ISSUE_LABELS"
