name: Test frontend
on:
  pull_request:
    branches:
      - master
jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install and Run Tests
        working-directory: frontend
        run: |
          npm ci
          npm run test